# Generated by Django 4.1.7 on 2023-04-08 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farm_date_creation_farm_alter_parcel_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='date_creation_farm',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_creation_parcel',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
