# Generated by Django 4.1.7 on 2023-05-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_date_creation_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='number_of_parcel',
            field=models.IntegerField(default=0),
        ),
    ]
