# Generated by Django 4.1.7 on 2023-05-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_alter_farm_latitude_alter_farm_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
