# Generated by Django 4.1.7 on 2023-03-22 03:13
# Generated by Django 4.1.7 on 2023-03-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('pasword', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
