# Generated by Django 4.1.7 on 2023-04-06 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='NIT',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,20}$', 'Enter a valid national ID (up to 20 digits)')]),
        ),
    ]
