# Generated by Django 4.1.7 on 2023-04-09 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seeds', '0002_alter_seeds_cbd_alter_seeds_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smell_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedSmell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.seeds')),
                ('smell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed_properties.smell')),
            ],
        ),
        migrations.CreateModel(
            name='SeedFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed_properties.flavor')),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.seeds')),
            ],
        ),
        migrations.CreateModel(
            name='SeedEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed_properties.effect')),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.seeds')),
            ],
        ),
    ]
