# Generated by Django 4.1.7 on 2023-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cbd', models.FloatField()),
                ('thc', models.FloatField()),
                ('species_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
