# Generated by Django 4.1.7 on 2023-06-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('cbd', models.FloatField()),
                ('thc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GrowingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowering_time', models.IntegerField(null=True)),
                ('harvest_time', models.IntegerField(null=True)),
                ('grow_dificulty', models.CharField(choices=[('Low', 'Low'), ('Medium low', 'Medium low'), ('Medium', 'Medium'), ('Medium high', 'Medium high'), ('High', 'High'), ('Very high', 'Vey high')], default=None, max_length=30)),
                ('yield_outdoor', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('yield_indoor', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.seeds')),
            ],
        ),
    ]
