# Generated by Django 4.1.7 on 2023-03-29 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='cbd',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='thc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.CreateModel(
            name='GrowingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowering_time', models.IntegerField(null=True)),
                ('harvest_time', models.IntegerField(null=True)),
                ('grow_dificulty', models.CharField(choices=[('Low', 'Low'), ('Medium low', 'Medium low'), ('Medium', 'Medium'), ('Medium high', 'Medium high'), ('High', 'High'), ('Very high', 'Vey high')], default=None, max_length=30)),
                ('yield_outdoor', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('yield_indoor', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.seeds')),
            ],
        ),
    ]
